plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'nvh.run'
version = '0.0.1-SNAPSHOT'


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-cache'

    // https://mvnrepository.com/artifact/io.lettuce/lettuce-core
    implementation 'io.lettuce:lettuce-core:6.6.0.BETA2'

    // https://mvnrepository.com/artifact/org.springframework.data/spring-data-redis
    implementation 'org.springframework.data:spring-data-redis:4.0.0-M1'

    // https://mvnrepository.com/artifact/it.ozimov/embedded-redis
    testImplementation 'it.ozimov:embedded-redis:0.7.1'

//    runtimeOnly 'com.google.apis:google-api-services-androidpublisher:v3-rev142-1.25.0'

    // for driver
//    implementation 'com.google.http-client:google-http-client-jackson2:1.46.1'

    implementation 'com.google.auth:google-auth-library-oauth2-http:1.32.1'

    implementation 'com.google.api-client:google-api-client:1.35.2'
    implementation 'com.google.apis:google-api-services-drive:v3-rev197-1.25.0'

    implementation 'com.google.oauth-client:google-oauth-client-jetty:1.37.0'

    implementation 'org.springframework.boot:spring-boot-starter-mail:3.4.2'

    implementation 'com.cloudinary:cloudinary-http5:2.0.0'
    implementation 'com.cloudinary:cloudinary-taglib:2.0.0'
    implementation 'io.github.cdimascio:dotenv-java:2.2.4'

    implementation 'org.mapstruct:mapstruct:1.6.3'//map
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.2'//convert

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'//swagger
    implementation 'org.springdoc:springdoc-openapi-ui:1.8.0'//swagger

    implementation 'org.bouncycastle:bcpkix-jdk15on:1.68'//decrypt rsa key
    implementation 'io.github.cdimascio:java-dotenv:5.2.2'//load env
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'//jwt
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'//jwt
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'//jwt
    implementation 'com.nimbusds:nimbus-jose-jwt:10.0.1'//decrypt
    implementation 'org.bouncycastle:bcprov-jdk18on:1.79'//decrypt
    implementation 'org.springframework.security:spring-security-core:6.4.2'//spring security
    developmentOnly 'org.springframework.boot:spring-boot-devtools'//auto restat app when code change
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'//interact mongo
    implementation 'org.springframework.boot:spring-boot-starter-security'//
    implementation 'org.springframework.boot:spring-boot-starter-validation'//validate
    implementation 'org.springframework.boot:spring-boot-starter-web'//web rest
    compileOnly 'org.projectlombok:lombok'//getter,setter
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
bootJar {
    mainClass = 'nvh.run.ideaswap.IdeaSwapApplication'
}

springBoot {
    mainClass = 'nvh.run.ideaswap.IdeaSwapApplication'
}
jar {
    manifest {
        attributes(
                'Main-Class': 'nvh.run.ideaswap.IdeaSwapApplication'
        )
    }
}


tasks.named('test') {
    useJUnitPlatform()
}
