spring.application.name=IdeaSwap
spring.profiles.active=Production
server.port=${PORT:8080}
jwt.password=abCD@1234
jwt.ACCESS_TOKEN_VALID_DURATION=3600000
jwt.REFRESH_TOKEN_VALID_DURATION=86400000
## JWT Configuration ##
#jwt.secret = 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
#jwt.expiration = 36000000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL:default_email.com}
spring.mail.password=${EMAIL_PASSWORD:default_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
