spring.application.name=IdeaSwap
spring.profiles.active=local
server.port=${PORT:8080}
jwt.password=abCD@1234
jwt.ACCESS_TOKEN_VALID_DURATION=3600000
jwt.REFRESH_TOKEN_VALID_DURATION=86400000
## JWT Configuration ##
#jwt.secret = 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
#jwt.expiration = 36000000

google.drive.folder-id=1zHatmu2Zyt00G9wjNJ3I_uh5MkSvDHSp
google.drive.service-account-key=ideaswap-70d2c30d8571.json

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL}
spring.mail.password=${EMAIL_PASSWORD}

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=nvhai227@gmail.com
#spring.mail.password=cwahltnnqmzmbulm

#spring.mail.username=${EMAIL:nvhai227@gmail.com}
#spring.mail.password=${EMAIL_PASSWORD:"cwah ltnn qmzm bulm"}
spring.google-cloud.driver.client-id=${CLIENT_ID:default-secret}
spring.google-cloud.driver.client-secret=${CLIENT_SECRET:default-secret}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
